### ISSUE TITLE
Edit close button text

### ISSUE THREAD

**Issue by Pannkaaka** [icemanbsi/searchable_dropdown#12]
Please allow us the edit the close button text.

**Comment by Pannkaaka** [comment]
Or actually, why not give the ability to just remove it?

**Comment by lcuis** [comment]
Hello @Pannkaaka ,
The close button text can be edited through the `closeButtonText` parameter. However, this is available only in the github version for now as it is not yet published to pub.dev. Until publication, you can use the following in your pubspec.yaml:
```
  searchable_dropdown:
    git:
      url: https://github.com/icemanbsi/searchable_dropdown.git
```

**Comment by Pannkaaka** [comment]
Sweet, thanks!

**Comment by lcuis** [comment]
You’re welcome!
