### ISSUE TITLE
Null safety support 

### ISSUE THREAD

**Issue by leynier** [icemanbsi/searchable_dropdown#121]
I will make a PR with null safety support implementation

**Comment by lcuis** [comment]
Thanks @leynier 
If it helps, this is done for the `search_choices` plugin.

**Comment by BringTheChill** [comment]
I did this PR. :) Enjoy!

**Comment by giorgio79** [comment]
Looks like the PR is failing some tests.

**Comment by BringTheChill** [comment]
> Looks like the PR is failing some tests.

yes, but this is a problem just if you want to use it for linux platform

**Comment by giorgio79** [comment]
I was just checking out the https://github.com/lcuis/search_choices fork, so I assume we should be going with that fork?

**Comment by BringTheChill** [comment]
> I was just checking out the https://github.com/lcuis/search_choices fork, so I assume we should be going with that fork?

you can do whatever you want

**Comment by omejiasq** [comment]
Hi guys, anybody know how to fix this issue in the searchable_dropdown flutter plugin? or anybody can tell me please which other dropdown with search can i to use ?
