### ISSUE TITLE
Remove default padding

### ISSUE THREAD

**Issue by pg598595** [icemanbsi/searchable_dropdown#143]
How to remove this default padding from the drop-down,
I tried to keep Sizedbox and container with fixed height but it is also not working
![image](https://user-images.githubusercontent.com/25722093/124593060-d0c75480-de7b-11eb-8331-6e2a64867cb4.png)

**Comment by lcuis** [comment]
Maybe this solves your issue?
https://github.com/lcuis/search_choices/pull/27

**Comment by pg598595** [comment]
Yes, Thanks
