### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gulsenkeskin** [icemanbsi/searchable_dropdown#154]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/searchable_dropdown-1.1.3/lib/searchable_dropdown.dart:371:41: Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
          ? Theme.of(context).textTheme.subhead
                                        ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/searchable_dropdown-1.1.3/lib/searchable_dropdown.dart:374:16: Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
              .subhead
               ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/searchable_dropdown-1.1.3/lib/searchable_dropdown.dart:832:25: Error: The getter 'FlatButton' isn't defined for the class '_DropdownDialogState<T>'.
 - '_DropdownDialogState' is from 'package:searchable_dropdown/searchable_dropdown.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/searchable_dropdown-1.1.3/lib/searchable_dropdown.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FlatButton'.
                return (FlatButton.icon(
                        ^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/searchable_dropdown-1.1.3/lib/searchable_dropdown.dart:993:17: Error: The method 'FlatButton' isn't defined for the class '_DropdownDialogState<T>'.
 - '_DropdownDialogState' is from 'package:searchable_dropdown/searchable_dropdown.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/searchable_dropdown-1.1.3/lib/searchable_dropdown.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FlatButton'.
                FlatButton(
                ^^^^^^^^^^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:searchable_dropdown

For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by lcuis** [comment]
Hello @gulsenkeskin ,

Thanks for reporting this issue. You may want to consider a more recently updated plugin such as search_choices for example. It is mostly compatible.

**Comment by gulsenkeskin** [comment]
I'm using it now, it works fine. Thank you very much.

**Comment by lcuis** [comment]
Thanks for your confirmation @gulsenkeskin !
