### ISSUE TITLE
TextStyle does not apply to searchbox

### ISSUE THREAD

**Issue by parkeradam** [icemanbsi/searchable_dropdown#31]
Supplied a text style however this is not being passed through and picked up in the searchbox leading to large dropdown items but a tiny searchbox.
<img width="371" alt="Screenshot 2020-03-31 at 09 34 34" src="https://user-images.githubusercontent.com/30392071/78005144-0dc8a100-7333-11ea-8a7b-cb23458fc79f.png">

**Comment by lcuis** [comment]
Hello @parkeradam ,

Thanks for reporting your issue.

To format the list of items, I'd recommend adapting the list of items you provide by changing the `child` element of the `DropdownMenuItem` objects.
For example:
```dart
...
items: Iterable<int>.generate(20).toList().map((i) {
          return (DropdownMenuItem(
            child: Text(i.toString(), style: yourStyle),
            value: i.toString(),
          ));
        }).toList(),
...
```

**Comment by parkeradam** [comment]
Hi @lcuis , It's not the DropdownMenuItems that are the issue (those are already styled). It's the search bar text that cannot seem to be styled, as you can see, I have an 'f' in the search bar but it is very small in comparison to the DropdownMenuItems. I want to be able to increase the font size inside of the search bar.

Sorry for any confusion and thanks for helping out :)

**Comment by lcuis** [comment]
Hi @parkeradam ,

Sorry, I misunderstood. Thanks for the clarifications.

Indeed, this is a missing feature at the moment. Maybe this will come in the future?
In the meanwhile, maybe there could be a solution through the themes?

**Comment by viniciuspn** [comment]
Good morning I have the same problem. I'm not able to change the color of the text or the icon.

...
"Historical example": SearchableDropdown(
        items: bankBRList.toList().map((value) {
          return (DropdownMenuItem(
            child: Text(value,
                style: TextStyle(
                  color: Colors.white, //Cor da lista de bancos,
                  fontSize: 14.0,
                )),
            value: value,
          ));
        }).toList(),
        value: selectedValue,
        hint: Text(false
            ? 'controllerBanco.text'
            : 'banco'), //validaTexto ? controllerBanco.text : banco,
        menuBackgroundColor: Colors.amber, //cor fundo da lista de banco
        closeButton: null,
        icon: Icon(Icons.keyboard_arrow_down),
        iconEnabledColor: Colors.black, //cor icone,
        searchHint: new Text(
          'Selecione seu Banco',
          style: new TextStyle(color: Colors.white, fontSize: 20),
        ),
        onChanged: (value) {
          setState(() {
            selectedValue = value;
          });
        },
        isExpanded: true,
      ),
...

**Comment by grab-a-byte** [comment]
This issue is resolved in :- https://github.com/lcuis/search_choices/pull/35 <- Library here seems to be maintained, usae this instead.
