### ISSUE TITLE
Overflow with long text

### ISSUE THREAD

**Issue by Laban1** [icemanbsi/searchable_dropdown#4]
Hi,

I tried using your dropdown in my app (two side-by-side), but both of them are overflowing if the text is too long (this was not happening with the DropdownButtonFormField, etc. that I was using before).  Here is a screenshot:

![searchableDropDownOverflowIssue](https://user-images.githubusercontent.com/9595654/67134490-492d4400-f1c7-11e9-8f44-662662293dfa.jpg)

Attached is a modified version of your main.dart sample file (renamed to main.txt so that I could attach it).

If you could fix this, it would be great - this is the best drop-down component that I have found so far, apart from this issue.

[main.txt](https://github.com/icemanbsi/searchable_dropdown/files/3745966/main.txt)

**Comment by icemanbsi** [comment]
Hi, your code is already good enough. You can add `isExpanded: true` option for both SearchableDropdown widget. And the overflow would be solved. Here is a sample:
`Expanded(
                    flex: 1,
                    child: new SearchableDropdown(
                      items: items,
                      value: selectedValue,
                      isExpanded: true,
                      isCaseSensitiveSearch: true,
                      hint: new Text(
                        'Select One'
                      ),
                      searchHint: new Text(
                        'Select One',
                        style: new TextStyle(
                            fontSize: 20
                        ),
                      ),
                      onChanged: (value) {
                        setState(() {
                          selectedValue = value;
                        });
                      },
                    ),
                  ),`

**Comment by Laban1** [comment]
Great, thanks!
