### ISSUE TITLE
The dropdown value is not updating since the lasts updates

### ISSUE THREAD

**Issue by pcf3333** [icemanbsi/searchable_dropdown#41]
I used to have a flutter application with this searchable dropdown and when the value was changed to `null ` and `setState()` was called the dropdown would show the hint text. This is not happening any more.

So the problem is that even if I set `value: null; `  the value still shows the previous selected value... sounds crazy.

Any guesses why? Could I downgrade somehow to the 1.1.0 version to it back working as it did?

Huge thanks!

Pere

**Comment by lcuis** [comment]
Hello @pcf3333 ,

Thanks for raising this issue.

It shows there is a regression on the value update. So, for your issue, I see the following possibilities:

1) as you mentioned, downgrade.
2) wait for a fix (not planned yet).
3) if applicable, make use of the clear button to set the value to null.
4) use the alternative plugin `search_choices` with the `single` constructor.

Sorry for the inconvenience.

**Comment by pcf3333** [comment]
Thanks so much for your answer. I ended up downgrading to version 1.1.0.
