### ISSUE TITLE
Search dialog is too big in web. Is there a way to get search without this dialog I mean just by typing like in autocomplete

### ISSUE THREAD

**Issue by geriby23** [icemanbsi/searchable_dropdown#43]
<img width="1680" alt="Screenshot 2020-04-16 at 17 45 39" src="https://user-images.githubusercontent.com/29865863/79470462-17782700-800a-11ea-92eb-9535cb84529a.png">

**Comment by lcuis** [comment]
At the moment, the web doesn't seem to support the menu mode of the searchable_dropdown, thus, the dialog is, for now, necessary in web. This is a bug that would need to be solved.

You can adapt the search/filter behavior through the searchFn argument. This way, it can probably be used more like an autocomplete than a search in terms of functionality (not display).

Sorry, at the moment, there is no way to reduce the size of the dialog. A boxConstraints argument would be a good idea for the dialog. It exists but only for the menu.

**Comment by geriby23** [comment]
@lcuis Thanks a lot for your response. Seems I was able to run menu mode. And it looks pretty nice.
But I have a couple of other issues I'm struggling to solve.
<img width="822" alt="Screenshot 2020-04-16 at 23 08 02" src="https://user-images.githubusercontent.com/29865863/79501685-21fce580-8037-11ea-986c-9357402cdbc4.png">
As you can see I have 3 dropdown fields. And when I select a country or province I need to clear dropdowns that are below.  It clears fine. But for example
I have selected some province and I have changed the country to another one.
It seems like dropdowns remember on which index it was and when the response with another country's provinces comes it sets by default province with the same list index as it was. And if this index is bigger than I had in a list that just came it. will crash with "out of index".
Also why after an item was selected field gets this big height. Is there a way to prevent it's size changes?

**Comment by lcuis** [comment]
Hi @geriby23 !

Good for you for the menu mode in web. Sorry, I forgot to mention that this works when you run it from Android Studio but not when it is hosted like for example on
https://searchchoices.jod.li
or
https://fluttertest-576ea.web.app

Yes, the selected value doesn't seem to update properly when this is done from outside the plugin. This is another bug that would also need to be addressed. There is a way however through an alternative version of the plugin: `search_choices`

The menu graphic size can be controlled through the `menuConstraints` argument.

**Comment by geriby23** [comment]
@lcuis I see. Anyway thanks for the help, it's really cool widget, I hope you guys will fix those bugs for the web and it would be really nice. 
I'll probably try to adapt search_choices right now.

**Comment by lcuis** [comment]
Thanks @geriby23 . Yes, it would be great to find time for those 2 bugs.

**Comment by lcuis** [comment]
Hi @geriby23 ,

As mentioned in `search_choices` plugin, there was a bug on hosted web that prevented the opening of the selection in menu mode.

This has been fixed with PR #45 .
Note that this is not yet merged and not deployed to pub.dev but that's on the way.

Also, it might be that the update issue that you have could be solved by the PR #26 that is merged but not yet published to pub.dev .

**Comment by geriby23** [comment]
Great!!!
Thanks, @lcuis !!!

**Comment by lcuis** [comment]
You're welcome!
