### ISSUE TITLE
Setting a preselected value with "value" - selecting other values has no effect

### ISSUE THREAD

**Issue by giorgio79** [icemanbsi/searchable_dropdown#48]
Hello,

When I set a preselected value via "value" I am unable to select other values as the selected value is always the preselected one.

```
                    child: SearchableDropdown.single(
                        value: "USD",
                        items: ["USD", "EUR", "CHF", "HUF"]
```

**Comment by giorgio79** [comment]
PS sorry, I realised we need to set the value before the build function...
```

var preselected = "USD";

  @override
  Widget build(BuildContext context) {
...
value: preselected.
```

**Comment by boungly** [comment]
@giorgio79 can you share your code snippet on selecting preSelectedValue? Because I've did that and doesn't seem to work.

**Comment by taufiqridha** [comment]
+1 im also having this problem, when using it with class from API to the searchable dropdown @boungly @giorgio79

**Comment by palicka** [comment]
I've managed to solve it by setting UniqueKey for this widget:
```
build() {
.....
      return SearchableDropdown.single(
        key: UniqueKey(),
....
}
```
It's not beautiful solution, but it looks like it's working. Maybe it will help someone...
