### ISSUE TITLE
Feature request: optional X to clear value (set to null).

### ISSUE THREAD

**Issue by Laban1** [icemanbsi/searchable_dropdown#5]
It would be very useful if the control had an option to display an X or similar next to the dropdown icon (or somewhere) to clear out the value, preferably with an onClear event...

**Comment by lcuis** [comment]
Hello @Laban1 ,
I had the same need, so I created a pull request:
https://github.com/icemanbsi/searchable_dropdown/pull/8
I hope this can be useful to you.

**Comment by icemanbsi** [comment]
@Laban1 , the PR from @lcuis  has been merged.

**Comment by lcuis** [comment]
Thanks @icemanbsi !
